replicaCount: 1

image:
  repository: alpine
  pullPolicy: Always
  # IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumes: []
  # - name: test
  #   persistentVolumeClaim:
  #     claimName: test
  # - name: params
  #   configMap:
  #     name: test

volumeMounts: []
  # - name: test
  #   mountPath: /app/logs
  #   subPath: app-logs

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  additionalPorts: []
    # - port: 81
    #   targetPort: 81
    #   protocol: TCP
    #   name: backend

ingressRoute:
  enabled: true
  entryPoints: []
    # - web
    # - websecure
  host: ""
  tlsName: ""
  additionalRoutes: []
    # - kind: Rule
    #   match: Host(`host`) && PathPrefix(`/api`)
    #   middlewares:
    #     - name: stripprefix-api
    #   services:
    #     - name: service-name
    #       port: 80

job:
  enabled: false
  image:
    pullPolicy: IfNotPresent
  schedule: "* * * * *"
  nodeSelector: {}
  command: []
    # - php
    # - artisan
    # - schedule:run

hostLogs:
  enabled: false
  capacity: 5Gi

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
