# Default values for laravel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: r.dev.mb.js.cn/app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configMapMounts:
  - name: app
    volumeName: sha1
    mountPath: "/var/www/html/public/sha1"
    subPath: sha1
    items:
      - key: sha1
        path: sha1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  additionalPorts: []

ingressRoute:
  enabled: true
  entryPoints:
    - web
    - websecure
  host: app.dev.moveclub.cn
  tlsName: ""
  additionalRoutes: []

job:
  enabled: false
  image:
    pullPolicy: IfNotPresent
  schedule: "* * * * *"
  nodeSelector: {}
  command:
    - php
    - artisan
    - schedule:run

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
