fullnameOverride: example-app

image:
  repository: nginx
  pullPolicy: Always
  # IfNotPresent
  tag: alpine

volumes: []
  # - name: config
  #   configMap:
  #     name: config
  #     items: 
  #       - key: sha1
  #         path: sha1.txt
  # - name: log-path
  #   hostPath:
  #     type: DirectoryOrCreate
  #     path: /data/logs/app-name

volumeMounts: []
  # - name: config
  #   mountPath: /var/www/html/public/sha1.txt
  #   subPath: sha1.txt
  # - name: log-path
  #   mountPath: /app/storage/logs

envs:
  TZ: Asia/Shanghai

ingressRoute:
  enabled: true
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`example-app`)
      middlewares:
        - name: log-request
      services:
        - name: example-app
          port: 80
  tls: {}
    # secretName: ""

command: []

cron:
  enabled: false
  serviceAccountName: job
  image: bitnami/kubectl:latest
  nodeSelector: {}
  jobs: 
    - schedule: "* * * * *"
      name: "job"
      command: kubectl exec deploy/example-app -- su www-data -s /bin/sh -c 'php artisan schedule:run'

tasks:
  enabled: false
  serviceAccountName: job
  nodeSelector: {}
  commands:
    - name: whoami
      sleep: 10
      command: kubectl exec deploy/example-app -- su www-data -s /bin/sh -c 'whoami'

service:
  type: ClusterIP
  port: 80
  additionalPorts: []
    # - port: 81
    #   targetPort: 81
    #   protocol: TCP
    #   name: backend

env:
  # - name: TZ
  #   value: Asia/Shanghai

envFrom: []
  # - configMapRef:
  #     name: test
  # - secretRef:
  #     name: test

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 5"]
  # postStart:
  #   exec:
  #     command: ["sh", "-c", "chown -R www-data:www-data /app/storage"]

startupProbe:
  exec:
    command: ["ls", "/tmp"]
  initialDelaySeconds: 5
  periodSeconds: 5

imagePullSecrets: []
nameOverride: ""

replicaCount: 1

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

resources: {}

tolerations: []

affinity: {}
