replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # IfNotPresent
  tag: alpine

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumes: []
  # - name: config
  #   configMap:
  #     name: config
  #     items: 
  #       - key: env
  #         path: .env
  #       - key: sha1
  #         path: sha1.txt
  # - name: log-file
  #   hostPath:
  #     type: DirectoryOrCreate
  #     path: /data/logs/app-name
  # - name: nginx-conf
  #   configMap:
  #     name: nginx-default

volumeMounts: []
  # - name: config
  #   mountPath: /app/.env
  #   subPath: .env
  # - name: config
  #   mountPath: /var/share/nginx/html/sha1.txt
  #   subPath: sha1.txt
  # - name: log-file
  #   mountPath: /app/storage/logs
  # - name: nginx-conf
  #   mountPath: /etc/nginx/conf.d
  #   readOnly: true

envFrom: []
  # - configMapRef:
  #     name: test
  # - secretRef:
  #     name: test

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  additionalPorts: []
    # - port: 81
    #   targetPort: 81
    #   protocol: TCP
    #   name: backend

ingressRoute:
  enabled: true
  entryPoints:
    - websecure
    - web
  host: ""
  tlsName: ""
  middlewares: []
  additionalRoutes: []
    # - kind: Rule
    #   match: Host(`host`) && PathPrefix(`/api`)
    #   middlewares:
    #     - name: stripprefix-api
    #   services:
    #     - name: service-name
    #       port: 80

job:
  enabled: false
  image:
    pullPolicy: IfNotPresent
  schedule: "* * * * *"
  nodeSelector: {}
  command: []
    # - php
    # - artisan
    # - schedule:run

lifecycle: {}
  # preStop:
  #   exec:
  #     command: ["sh", "-c", "sleep 5"]
  # postStart:
  #   exec:
  #     command: ["sh", "-c", "chown -R www-data:www-data /app/storage"]

startupProbe:
  exec:
    command: ["ls", "/tmp"]
  initialDelaySeconds: 5
  periodSeconds: 5

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
