{{- range .Values.cron.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Values.name }}-{{.name}}
spec:
  concurrencyPolicy: {{ .concurrencyPolicy | default "Forbid" }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: {{ $.Values.cron.image | default "bitnami/kubectl:latest" }}
              imagePullPolicy: IfNotPresent
              env:
                - name: KUBERNETES_SERVICE_HOST
                  value: "kubernetes.default.svc.cluster.local"
                - name: KUBERNETES_SERVICE_PORT
                  value: "443"
              name: {{ .name }}
              command:
                - sh
                - -c
                - {{ .command }}
          serviceAccountName: {{ $.Values.cron.serviceAccountName }}
          {{- with $.Values.cron.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: "{{ .schedule }}"
{{- end }}
