fullnameOverride: example-app

image:
  repository: nginx
  pullPolicy: Always
  # IfNotPresent
  tag: alpine

volumes: []
  # - name: config
  #   configMap:
  #     name: config
  #     items: 
  #       - key: sha1
  #         path: sha1.txt
  # - name: nginx-conf
  #   configMap:
  #     name: nginx-default

volumeMounts: []
  # - name: config
  #   mountPath: /var/share/nginx/html/sha1.txt
  #   subPath: sha1.txt
  # - name: nginx-conf
  #   mountPath: /etc/nginx/conf.d
  #   readOnly: true

ingressRoute:
  enabled: true
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`example-app`)
      services:
        - name: example-app
          port: 80
    # - kind: Rule
    #   match: Host(`example-app`) && PathPrefix(`/api`)
    #   middlewares:
    #     - name: stripprefix-api
    #     - name: log-request
    #   services:
    #     - name: example-app
    #       port: 80
  tls: {}
    # secretName: ""

service:
  type: ClusterIP
  port: 80

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 5"]

startupProbe:
  exec:
    command: ["ls", "/tmp"]
  initialDelaySeconds: 5
  periodSeconds: 5

imagePullSecrets: []
nameOverride: ""

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

resources: {}

tolerations: []

affinity: {}
