{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel.fullname" . }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.job.image.pullPolicy }}
              name: {{ include "laravel.fullname" . }}
              {{- with .Values.job.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          {{- with .Values.job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: "{{ .Values.job.schedule }}"
{{- end }}