{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel.fullname" . }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.job.image.pullPolicy }}
              name: {{ include "laravel.fullname" . }}
              {{- with .Values.job.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if .Values.configMapMounts }}
              volumeMounts:
                {{- range .Values.configMapMounts }}
                - name: {{ .name }}
                  mountPath: {{ .mountPath }}
                  {{- if .subPath }}
                  subPath: {{ .subPath }}
                  {{- end }}
                {{- end }}
              {{- end }}
          {{- if .Values.configMapMounts }}
          volumes:
            {{- range .Values.configMapMounts }}
            - name: {{ .name }}
              configMap:
                name: {{ .name }}
                items:
                  {{- range .items }}
                  - key: {{ .key }}
                    path: {{ .path }}
                  {{- end }}
            {{- end }}
          {{- end }}
          restartPolicy: Never
          {{- with .Values.job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  schedule: "{{ .Values.job.schedule }}"
{{- end }}