{{- if .Values.tasks.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
spec:
  selector:
    matchLabels:
      tasks: {{ include "app.fullname" . }}
  serviceName: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        tasks: {{ include "app.fullname" . }}
    spec:
      containers:
        {{- range $index, $task := .Values.tasks.commands }}
        - name: task-{{ $index }}-{{ $task.name }}
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc.cluster.local"
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
          command:
            - sh
            - -c
            - while true; do {{ $task.command }}; sleep {{ $task.sleep | default 10 }} ; done
        {{- end }}
      serviceAccountName: {{ .Values.tasks.serviceAccountName }}
{{- end }}
